name: drivrr_driver
description: "Drivrr Driver App - InDrive-style ride hailing for drivers"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  provider: ^6.1.1

  # Navigation
  go_router: ^12.1.3

  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # Maps & Location (flutter_map - pure Dart implementation)
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  routing_client_dart: ^1.0.7
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  socket_io_client: ^2.0.3+1
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Utils
  uuid: ^4.2.1
  
  # Image & File Handling
  image_picker: ^1.0.4
  # image_cropper: ^8.0.2  # Temporarily disabled due to compatibility issues
  camera: ^0.10.6
  path: ^1.8.3
  mime: ^1.0.4
  
  # Document processing & edge detection
  opencv_dart: ^1.0.4
  
  path_provider: ^2.1.3
  flutter_image_compress: ^2.3.0

  # High-performance, native document scanning
  flutter_document_scanner: ^1.1.2

  # Keep these for OCR processing after capture
  google_mlkit_text_recognition: ^0.13.0
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/