name: drivrr_driver
description: "Drivrr Driver App - InDrive-style ride hailing for drivers"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # Navigation
  go_router: ^12.1.3

  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # Maps & Location (flutter_map - pure Dart implementation)
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  routing_client_dart: ^1.0.7
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  socket_io_client: ^2.0.3+1
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Utils
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/